branches:
  only:
    - master
git:
  depth: 3
language: node_js
node_js:
- lts/*
install: true
script: true
deploy:
- provider: npm
  email: levy9527@qq.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
